name: Node.js CI

on:
  push:
    paths:
      - 'js/**'
      - '.github/workflows/nodejs-ci.yml'

jobs:
  nodejs-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./js
        run: npm install

      - name: Run JS tests
        working-directory: ./js
        run: npm test
