name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ตั้งค่า Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ติดตั้ง dependencies
        run: |
          pip install -r requirements.txt

      - name: รัน Unit Tests
        run: |
          pytest
